name: local_notifaiction
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutx:
    path: ../flutx  


 
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_local_notifications: ^9.1.4
#  flutter_native_timezone: ^1.0.8
  flutter_native_timezone:
  #^2.0.0
  get_storage: ^2.0.3
  nb_utils: ^4.4.0
  get: ^4.3.8
  easy_localization: ^3.0.0

  intl: ^0.17.0
  #this is for Custom DateTime    
  jiffy: ^4.1.0
  google_fonts:
  # date_picker_timeline:
  sqflite: ^2.0.1
  # flutter_staggered_animations:
  rxdart: ^0.26.0
  #   هذ  التي تعمل علا طلب البيانات بشكل تجزيئي مهمه جدا
  infinite_scroll_pagination: ^3.1.0
  awesome_dialog: ^2.1.1
  #this is style icons
  material_design_icons_flutter: ^5.0.5955-rc.1
  # this is radial  slider 
  syncfusion_flutter_gauges: ^19.3.56
  url_launcher: ^6.0.17
  # desktop_window: ^0.4.0
  # bottom_navy_bar: ^6.0.0
  # this is new
  # image: ^3.0.8
  # rxdart: ^0.27.3
  # device_info: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  # بعد اضافة ايقونه لتطبيق يجب حذف هذه المكتبة
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  # ios: true
  android: true
  image_path_ios: "images/launcher/foreground.png"
  image_path_android: "images/launcher/foreground.png"
  adaptive_icon_background: "images/launcher/background.png"
  adaptive_icon_foreground: "images/launcher/foreground.png"

flutter:


  uses-material-design: true

  assets:
     - images/
     - images/shopping/
     - images/shopping/product/
     - images/shopping/offer/
     - images/shopping/vector/
     - images/shopping/camera/
      ##Grocery
     - images/grocery/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
          style: italic
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
